apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pvc
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /export/volme
    server: 172.31.41.22
