---   
apiVersion: v1
kind: Service
metadata:
  name: drupal-db
  labels:
    app: drupal
spec:
  ports:
    - port: 3306
  selector:
    app: drupal
    tier: backend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-pvc-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi  
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: drupal-mysql
  labels:
    app: drupal        
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal
        tier: backend
    spec:
      containers:
      - image: mysql:5.6
        imagePullPolicy: IfNotPresent
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: drupal-db
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-stateful-storage
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-stateful-storage
          persistentVolumeClaim:
            claimName: drupal-pvc-db
